### ISSUE TITLE
Generation of IPD submission files failed - user locked

### ISSUE THREAD

**Issue by steletvinicius** [DKMS-LSL/typeloader#16] opened 2020-02-20 16:58 UTC
Hi,

during the process of generating IPD submission files, TypeLoader returned the following error messages:

"Another user is currently creating IPD files.
Please try again in a minute or so, to make sure you don't create files with the same IPD number.
(Proceed anyway) "

"Are you REALLY sure no other user is currently creating IPD files and you can continue safely?
(Yes)"

"UnboundLocalError("local variable 'gene' referenced before assignment",) "

After deciding to restart the system, during the logging process
Typeloader returned another error message (that I had not copied).
It says something about the user to be already active/in use.

Only after clicking on "Remove user lock", login in was made possible.

But the IPD submission is still returning the same error messages.

How should I proceed to solve that problem?

**Comment by bmschoene** [comment] 2020-02-24 08:28
There are multiple issues at work here. You are the only TypeLoader user in your lab, right? Then the "Another user is currently creating IPD files." error occured because there was some kind of crash/hickup/error during the last time you created IPD files.

To get out of it, click the "yes" to "Are you REALLY sure no other user is currently creating IPD files and you can continue safely?". It should then continue safely. 

(As you may have noticed, TypeLoader assigns submission numbers to the files generated for IPD. This number is stored in a file shared among TypeLoader users of the same lab. So to make sure that the same numbers are not assigned multiple times because several users are creating IPD files simultaneously, there is a lock created whenever someone starts creating IPD files. This is removed when the file creation is successful or reaches a known error. But if a crash occurs, it remains and you get this message the next time you try to create IPD files. Clicking the button removes it so you can proceed again.) 

The "This login is currently used" message happens if TypeLoader was not correctly shut down/crashed the last time you were logged in. Removing the user lock, as you did, is the right way to proceed here. (This works similarly to the IPD lock and prevents multiple people logging into the same account simultaneously.)

The real problem is probably the "UnboundLocalError("local variable 'gene' referenced before assignment",)". For this, I can't say from here what the specific problem is. :-(

Can you attach the fasta/xml file this allele is based on, so I can check if I can reproduce this? I've been fixing a lot of bugs lately (still working on the upcoming release), maybe it's already fixed - and if not, i can hopefully fix it within the release.

Alternativley, you could send me a logfile and I could try to see what happened. You can find your logfiles under <place where TypeLoader stores its data (assigned during setup)>\<your username>\recovery . You could maybe create a clean one by restarting TypeLoader and proceeding with the minimal steps that lead to this error, then closing TypeLoader. The logfiles are named with the timestamp of the TypeLoader session start - choosing the latest is usually the way to go. 
You might want to check it with a text editor to remove file paths that you don't want exposed...

**Comment by bmschoene** [comment] 2020-03-02 11:37
Does this issue still persist?

I have just uploaded the new release. Please check if it still comes up with this. If yes, you now have the option to download a log file (Menu => Options => Download log file). That might help us see what actually went wrong.

**Comment by steletvinicius** [comment] 2020-03-04 13:28
Sorry for the delay!

I have decided to update TypeLoader (version 2.7) and check if everything is fine.

I was able to run ENA submissions and generate IPD files for a single project
which is a partial solution for the impeditive error 
"UnboundLocalError("local variable 'gene' referenced before assignment",) "

However, some error messages persist and might demand some additional interventions
as you can see in the log files below.

[20200304_091511.log](https://github.com/DKMS-LSL/typeloader/files/4287476/20200304_091511.log)
[20200303_154339.log](https://github.com/DKMS-LSL/typeloader/files/4287477/20200303_154339.log)

Most importantly: Typeloader is running and I can restart my submissions to IPD. Thanks!

**Comment by bmschoene** [comment] 2020-03-05 08:27
I don't see any erro in these log files. They look like you successfully created IPD files?

Can you please specify which messages you see that you don't expect, and after doing exactly what? And ideally, do a TypeLoader session (= restart TypeLoader) where you only perform the minimal steps leading to this error, and then send the log?

I'm sure we can figure this out and get it fixed. :-)

**Comment by bmschoene** [comment] 2020-05-26 08:06
@steletvinicius Does this issue still occur?

**Comment by steletvinicius** [comment] 2020-05-26 12:22
@bmschoene TypeLoader is running with no problems. The issue is gone.

I just want to say thank you for keeping TypeLoader available for the HLA community.
Based on my experience, TypeLoader facilitates the submission process to IPD-IMGT/HLA database, mainly for situations where you have many sequences to submit.
In addition to that, Typeloader helps post submissions tracking setting me free of those Excel spreadsheets!

Since de January 2020, it has been 118 submissions to IMGT, most of them intronic novelties! : -)

**Comment by bmschoene** [comment] 2020-05-26 12:45
Awesome! 
Thanks for the feedback! :-)

**Closed by bmschoene** 2020-05-26 12:45 UTC
