### ISSUE TITLE
Execution in Ubuntu 20.04 failes  Problem with PyQt5 (QtSql not found)

### ISSUE THREAD

**Issue by dfuerst1** [DKMS-LSL/typeloader#34] opened 2023-02-14 08:30 UTC
Python version 3.8.10 ist installed and PyQt5 also
Error message when executing  typeloader_GUI.py

raceback (most recent call last):
  File "typeloader_GUI.py", line 32, in <module>
    import GUI_forms_new_project, GUI_forms_new_allele, GUI_forms_new_allele_bulk
  File "/home/dfuerst/typeloader-master/typeloader2/GUI_forms_new_project.py", line 16, in <module>
    from PyQt5.QtSql import QSqlQuery
ModuleNotFoundError: No module named 'PyQt5.QtSql'

In Python shell:

Python 3.8.10 (default, Nov 14 2022, 12:59:47) 
[GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from PyQt5 import QtSql
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'QtSql' from 'PyQt5' (/usr/lib/python3/dist-packages/PyQt5/__init__.py)

QtSql module is not present.

Is there a solution for this problem?

**Comment by bmschoene** [comment] 2023-02-14 08:50
Probably.
What operating system are you using? How did you do setup?

**Comment by bmschoene** [comment] 2023-02-15 11:52
Please let me know whether this fixed your problem.

Feedback from an (eventually) successful Linux installation would be very helpful for the update of the Linux setup documentation.

**Comment by dfuerst1** [comment] 2023-02-15 15:24
Poetry required python3.10 so I installed and switched to python3.10
and installed the dependencies. 
No a different issue occured:

python3 typeloader_GUI.py

Traceback (most recent call last):
  File "/home/dfuerst/typeloader-master/typeloader2/typeloader_GUI.py", line 22, in <module>
    from PyQt5.QtWidgets import (QMainWindow, QApplication, QDialog,
ModuleNotFoundError: No module named 'PyQt5.QtWidgets'

**Comment by dfuerst1** [comment] 2023-02-15 15:49
Maybe it is nevessary to switch to python3.6

**Comment by bmschoene** [comment] 2023-02-15 18:33
It shouldn't be - I'm developing TypeLoader on Python 3.10.4.
PyQt seems to behave weirdly on Linux. Which is odd, because it's supposed to work... 
I'll try to find a Linux machine to figure this out next week. 

Sorry for the inconvenience!

**Comment by bmschoene** [comment] 2023-02-15 18:34
Oh, wait. Did you do `poetry shell` to activate the virtual environment created by poetry, before you ran `python3  typeloader_GUI.py` ?

**Comment by bmschoene** [comment] 2023-02-23 09:59
My Linux-savvy colleagues have investigated this problem, and we have a guess: did you perhaps try this on a machine that has only a command line but no GUI, or possibly within an ssh session?

TypeLoader is a GUI tool. You can start it from the command line, but you cannot *use* it from there, as all user interaction currently happens through the GUI. (We have thought about implementing a command line version, but so far it never reached a sufficiently high priority to justify the effort.)

So, if you're in an ssh session, use `export` to tell python where to forward the GUI stuff to.  Otherwise, please use  a machine that can display GUI applications.

Please let me know whether this fixes your problem!

**Comment by dfuerst1** [comment] 2023-02-23 10:38
Thank you for the help. Using the poetry shell worked.

**Comment by bmschoene** [comment] 2023-02-23 10:39
Great! Happy TypeLoader-using, then. :-)

**Comment by dfuerst1** [comment] 2023-02-23 10:41
I was able to read the test HLA-A fasta file. 
However when submitting to the ENA test server the process failed.

Is there a problem with the connection to ENA?

Traceback (most recent call last):
  File "/home/dfuerst/typeloader-master/typeloader2/GUI_forms_submission_ENA.py", line 359, in submit_to_ENA
    self.cleanup_submission_failed()
  File "/home/dfuerst/typeloader-master/typeloader2/GUI_forms_submission_ENA.py", line 365, in cleanup_submission_failed
    for key in self.file_dic:
AttributeError: 'ENASubmissionForm' object has no attribute 'file_dic'
Traceback (most recent call last):
  File "/home/dfuerst/typeloader-master/typeloader2/GUI_forms_submission_ENA.py", line 337, in submit_to_ENA
    results = submit_alleles_to_ENA(self.project_name, ENA_ID, self.samples, files, self.settings, self.log)
  File "/home/dfuerst/typeloader-master/typeloader2/typeloader_functions.py", line 1170, in submit_alleles_to_ENA
    ena_results, success, err_type, msg, problem_samples = submit_sequences_to_ENA_via_CLI(
  File "/home/dfuerst/typeloader-master/typeloader2/typeloader_functions.py", line 1100, in submit_sequences_to_ENA_via_CLI
    success, ENA_response, _, problem_samples = EF.handle_webin_CLI(ena_cmd, "validate", submission_alias,
  File "/home/dfuerst/typeloader-master/typeloader2/typeloader_core/EMBLfunctions.py", line 565, in handle_webin_CLI
    penultimate_line = output_list[-2]
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/dfuerst/typeloader-master/typeloader2/GUI_forms_submission_ENA.py", line 359, in submit_to_ENA
    self.cleanup_submission_failed()
  File "/home/dfuerst/typeloader-master/typeloader2/GUI_forms_submission_ENA.py", line 365, in cleanup_submission_failed
    for key in self.file_dic:
AttributeError: 'ENASubmissionForm' object has no attribute 'file_dic'
INFO [2023-02-23 11:33:00] - Cleaning up old recovery files...
DEBUG [2023-02-23 11:33:00] - Closing connection to db...
DEBUG [2023-02-23 11:33:00] - 	=> Connection closed
DEBUG [2023-02-23 11:33:00] - Removing lock...
DEBUG [2023-02-23 11:33:00] - 	=> done
INFO [2023-02-23 11:33:00] - <End>

**Comment by bmschoene** [comment] 2023-02-23 10:52
This

**Comment by dfuerst1** [comment] 2023-02-24 10:44
[20230223_114738.log](https://github.com/DKMS-LSL/typeloader/files/10823228/20230223_114738.log)

**Comment by dfuerst1** [comment] 2023-02-24 10:44
I created a user beginning with test which should connect to the testserver.
Maybe this connection is not working sufficiently

**Comment by bmschoene** [comment] 2023-02-24 14:04
No, the problem is with the ENA-Webin-CLI tool. That's a java file provided by ENA, which handles all communication with them.
Your log file says it's corrupt, for some reason.

Please try the following:
- Dowload the file [webin-cli-6.1.0.jar](https://github.com/enasequence/webin-cli/releases/download/6.1.0/webin-cli-6.1.0.jar) from ENA.
- Save it to the directory `typeloader2/ENA_Webin_CLI' within your `typeloader2` repo.
- Re-start TypeLoader & try again.

Let me know the outcome!

**Comment by bmschoene** [comment] 2023-02-24 14:36
Also, fyi: https://github.com/DKMS-LSL/typeloader/issues/35

I hope there will be a solution & subsequent TypeLoader release really soon. But it's not in our hands to say when ENA will deign to give us a working process. :-(

That doesn't mean you can't use TypeLoader, just that you probably currently won't be able to get past the "ENA submitted" stage. But as soon as we get a working process from ENA again, you'll be able to continue right there.

Really sorry about this.

**Comment by dfuerst1** [comment] 2023-02-27 09:16
With the file [webin-cli-6.1.0.jar](https://github.com/enasequence/webin-cli/releases/download/6.1.0/webin-cli-6.1.0.jar) 
the connection to ENA seems to work.

**Comment by bmschoene** [comment] 2023-02-27 09:33
Great! 
Then I'm closing this. Feel free to open a new issue if you encounter any other problems. :-)

**Closed by bmschoene** 2023-02-27 09:33 UTC
